project:
  type: website
  preview:
    port: 8329
    
website:
  title: "Advanced Predictive Models - STATS1234"
  search: false
  navbar:
    logo: apm.png
    logo-alt: "APM logo"
    right:
      - text: First Lab
        href: Lab1.qmd
      - text: Second Lab
        href: Lab2.qmd
      - text: Third Lab
        href: Lab3.qmd
      - text: Fourth Lab
        href: Lab4.qmd

format:
  html:
    css: counters.css
    theme:
      light: [cosmo, "scss/nav.scss", "scss/light.scss", "scss/questions.scss"]
      dark:  [darkly, "scss/nav.scss", "scss/dark.scss",  "scss/questions.scss"]
    respect-user-color-scheme: true